### ISSUE TITLE
rename README.md in week2 to something more applicable 

### ISSUE THREAD

**Issue by NataliaLKB** [foundersandcoders/fac5#9]
@rjmk would you be able to rename the frontend dev presentation from yesterday to something more content relevant.

Try naming it after the topic that was given to you. Like `http.md` or `ajax.md` or another relevant title.

Thanks so much! :+1:

**Comment by rjmk** [comment]
Now done! Let me know if it's not OK. :smile:

**Comment by iteles** [comment]
@rjmk In case you're not already aware, if you add the issue URL into your commit message, the commit is automatically referenced in the issue which is a good way of keeping track of which commits solved which issues  :blush:

**Comment by NataliaLKB** [comment]
@rjmk that is great! 

PR merged :+1: 

https://github.com/foundersandcoders/fac5/pull/5

**Comment by rjmk** [comment]
@iteles Cool, thanks! :)

@NataliaLKB Yay! :+1:
